name: Deploy Flutter Web to GitHub Pages
on:
  push:
    branches: [ "develop" ]
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 
    
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4
      
      - name: ☕ Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
<<<<<<< HEAD
          channel: stable
          flutter-version: '3.24.2'

      - name: 🌐 Enable Web
        run: flutter config --enable-web
=======
          channel: 'stable'
<<<<<<< HEAD
>>>>>>> develop

      # 4. Flutter 웹 설정 및 파일 생성
=======
          
      - name: ✍️ Create .env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
          echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> .env
          echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_JAVASCRIPT_KEY }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}" >> .env
          echo ".env 파일 생성 완료:"
          cat .env
          
>>>>>>> develop
      - name: 🌐 Configure Flutter for Web
        run: flutter create . --platforms web
        
      - name: 🧩 Get Dependencies
        run: flutter pub get
        
      # ⭐ --web-renderer 옵션 제거
      - name: 🏗️ Build Web App
        run: flutter build web --release --base-href "/FE/"
        
      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
